build:
  build:
    image: python:2
    commands:
      - echo "Build Phase"

publish:
  docker:
    repo: $$DOCKER_REPO
    tag: "$${BRANCH##feature/}"
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL

  docker:
    repo: $$DOCKER_REPO
    tag: "latest"
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    when:
      branch: "master"



notify:
  spark:
    image: hpreston/drone-spark:latest
    pull: true
    auth_token: $$SPARK_TOKEN
    roomId: $$SPARK_ROOM
    message: "##Build $$BUILD_NUMBER Successful. \n drone-spark has been built successfully. \n (http://$$DRONE_SERVER/$$DOCKER_REPO/$$BUILD_NUMBER) \n (https://github.com/$$DOCKER_REPO/commit/$$COMMIT) "
    when:
      success: true

  spark:
    image: hpreston/drone-spark:latest
    pull: true
    auth_token: $$SPARK_TOKEN
    roomId: $$SPARK_ROOM
    message: "##Build $$BUILD_NUMBER FAILED. \n drone-spark has been built successfully. \n (http://$$DRONE_SERVER/$$DOCKER_REPO/$$BUILD_NUMBER) \n (https://github.com/$$DOCKER_REPO/commit/$$COMMIT) "
    when:
      success: false