build:
  build:
    image: python:2
    commands:
      - echo "Build Phase"

publish:
  docker:
    repo: $$DOCKER_REPO
    tag: "$${BRANCH##feature/}"
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL


notify:
  spark:
    image: hpreston/drone-spark
    auth_token: $$SPARK_TOKEN
    roomId: $$SPARK_ROOM
    message: "##Spark Plugin. \n Repo $CI_REPO - Drone confirms $CI_REPO build $CI_BUILD_NUMBER completed successfully. \n http://github.com/$CI_REPO/commit/$CI_COMMIT. \n http://$$DRONE_SERVER/$CI_REPO/$CI_BUILD_NUMBER."
    when:
      success: true

  spark:
    image: hpreston/drone-spark
    auth_token: $$SPARK_TOKEN
    roomId: $$SPARK_ROOM
    message: "Spark Plugin. Repo {{repo.full_name}} - Drone blames {{build.author}} for breaking build {{build.number}}. \n http://github.com/{{repo.full_name}}/commit/{{build.commit}}. \n http://$$DRONE_SERVER/{{repo.full_name}}/{{build.number}}."
    when:
      success: false