build:
  build:
    image: python:2
    commands:
      - echo "Build Phase"

publish:
  docker:
    repo: $$DOCKER_REPO
    tag: "$${BRANCH##feature/}"
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL

  docker:
    repo: $$DOCKER_REPO
    tag: "latest"
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    when:
      branch: "master"



notify:
  spark:
    image: hpreston/drone-spark:latest
    pull: true
    auth_token: $$SPARK_TOKEN
    roomId: $$SPARK_ROOM
    message: "Great Job!!!"
    when:
      success: true

  spark:
    image: hpreston/drone-spark:latest
    pull: true
    auth_token: $$SPARK_TOKEN
    roomId: $$SPARK_ROOM
    message: "Poor form... you should be ashamed..."
    when:
      success: false