build:
  build:
    image: python:2
    commands:
      - echo "Build Phase"

notify:
  spark:
    image: hpreston/drone-spark
    auth_token: $$SPARK_TOKEN
    roomId: $$SPARK_ROOM
    message: "Spark Plugin. Repo $$CI_REPO - Drone confirms $$CI_REPO build $$CI_BUILD_NUMBER completed successfully.\nhttp://github.com/$$CI_REPO/commit/$$COMMIT.\nhttp://$$DRONE_SERVER/$$CI_REPO/$$CI_BUILD_NUMBER."
    when:
      success: true

  spark:
    image: hpreston/drone-spark
    auth_token: $$SPARK_TOKEN
    roomId: $$SPARK_ROOM
    message: "Spark Plugin. Repo {{repo.full_name}} - Drone blames {{build.author}} for breaking build {{build.number}}.\nhttp://github.com/{{repo.full_name}}/commit/{{build.commit}}.\nhttp://$$DRONE_SERVER/{{repo.full_name}}/{{build.number}}."
    when:
      success: false